# Generated by Django 5.2 on 2025-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('ProcurementManager', 'Procurement Manager'), ('DepartmentUser', 'Department User'), ('WarehouseHead', 'Warehouse Head'), ('WarehouseManager', 'Warehouse Manager')], max_length=20),
        ),
    ]
