# Generated by Django 5.2 on 2025-05-17 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_educationalproduct_sub_category'),
        ('purchase_requests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Rework Required', 'Rework Required'), ('Reviewed', 'Reviewed')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.educationalproduct'),
        ),
    ]
