# Generated by Django 5.2 on 2025-05-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0003_remove_purchaserequest_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='purchase_requests.purchaserequest'),
        ),
    ]
