# Generated by Django 5.2 on 2025-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0005_purchaserequeststatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='segment',
            field=models.CharField(choices=[('OIS', 'OIS'), ('B2B', 'B2B')], default='OIS', max_length=10, verbose_name='Segment'),
            preserve_default=False,
        ),
    ]
