# Generated by Django 5.2 on 2025-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0006_purchaserequest_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='segment',
            field=models.CharField(choices=[('OIS', 'OIS'), ('B2B', 'B2B'), ('OCSE', 'OCSE')], max_length=10, verbose_name='Segment'),
        ),
    ]
