# Generated by Django 5.2 on 2025-07-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_poitem_grnrecord'),
        ('purchase_requests', '0007_alter_purchaserequest_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
