# Generated by Django 5.2 on 2025-07-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='damage_return',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_reason_type',
            field=models.CharField(choices=[('DAMAGE', 'Damaged Stock'), ('EXCESS', 'Excess Found'), ('MISSING', 'Missing Stock'), ('RETURN', 'Customer Return'), ('EXPIRED', 'Expired Items'), ('CYCLE_COUNT', 'Cycle Count Correction'), ('TRANSFER', 'Transfer Adjustment'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='action_type',
            field=models.CharField(choices=[('RECEIPT', 'Goods Receipt'), ('ADJUST_ADD', 'Adjustment Add'), ('ADJUST_REMOVE', 'Adjustment Remove')], max_length=20),
        ),
        migrations.DeleteModel(
            name='StockIssue',
        ),
    ]
