# Generated by Django 5.2 on 2025-07-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_academicyear_inventoryitem_warehouse_and_more'),
        ('procurement', '0008_remove_purchaseorder_rfq_remove_purchaseorder_vendor_and_more'),
        ('products', '0003_alter_educationalproduct_segment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.educationalproduct')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GRNRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('damage_quantity', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.goodsreceipt')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_records', to='inventory.poitem')),
            ],
        ),
    ]
