# Generated by Django 5.2 on 2025-05-21 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_requests', '0005_purchaserequeststatushistory'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Approved', 'Approved'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Initiated', max_length=20)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_delivery', models.DateField()),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('delay_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_received', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='procurement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='purchase_requests.purchaserequest')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.rfq'),
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_requests.requestitem')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='procurement.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotations', to='procurement.rfqitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
