# Generated by Django 5.2 on 2025-05-22 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_vendorquotation_status_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorquotation',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='VendorBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vendorquotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='vendor_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.vendorbid'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorquotation',
            unique_together={('rfq_item', 'vendor_bid')},
        ),
        migrations.RemoveField(
            model_name='vendorquotation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vendorquotation',
            name='submitted_at',
        ),
    ]
