# Generated by Django 5.2 on 2025-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_remove_vendorquotation_vendor'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorbid',
            unique_together={('rfq', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='vendorbid',
            index=models.Index(fields=['rfq'], name='procurement_rfq_id_2d1b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbid',
            index=models.Index(fields=['vendor'], name='procurement_vendor__e39022_idx'),
        ),
    ]
