# Generated by Django 5.2 on 2025-05-28 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_vendorbid_unique_together_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorbid',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vendorbid',
            name='submission_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbid',
            unique_together={('rfq', 'vendor', 'submission_group')},
        ),
    ]
