# Generated by Django 5.2 on 2025-05-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_vendorbid_unique_together_and_more'),
    ]

    operations = [
    ]
