# Generated by Django 5.2 on 2025-05-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_auto_20250529_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.vendorbid'),
        ),
    ]
