# Generated by Django 5.2 on 2025-07-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_poitem_grnrecord'),
        ('procurement', '0008_remove_purchaseorder_rfq_remove_purchaseorder_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
