# Generated by Django 5.2 on 2025-07-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_purchaseorder_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Approved', 'Approved'), ('Dispatched', 'Dispatched'), ('Partially Received', 'Partially Received'), ('Delivered', 'Delivered')], default='Initiated', max_length=20),
        ),
    ]
