# Generated by Django 5.2 on 2025-07-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Warehouse',
            new_name='warehouse',
        ),
    ]
