# Generated by Django 5.2 on 2025-07-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_poitem_grnrecord'),
        ('products', '0004_alter_educationalproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('enrollment_code', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('student_class', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('paid_date', models.DateField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.educationalproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('academic_year', 'warehouse', 'enrollment_code', 'sku')},
            },
        ),
    ]
