# Generated by Django 5.2 on 2025-07-10 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_poitem_grnrecord'),
        ('orders', '0001_initial'),
        ('products', '0004_alter_educationalproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.educationalproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'Order Summaries',
                'unique_together': {('warehouse', 'grade', 'sku')},
            },
        ),
    ]
