# Generated by Django 5.2 on 2025-07-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_name', models.CharField(default='Default', max_length=100)),
                ('low_threshold', models.PositiveIntegerField(default=75)),
                ('medium_threshold', models.PositiveIntegerField(default=85)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procurement Threshold',
                'verbose_name_plural': 'Procurement Thresholds',
            },
        ),
    ]
