# Generated by Django 5.2 on 2025-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('ois', 'OIS'), ('b2b', 'B2B')], max_length=100)),
                ('year', models.CharField(choices=[('23-24', 'AY 23-24'), ('24-25', 'AY 24-25'), ('25-26', 'AY 25-26'), ('26-27', 'AY 26-27')], max_length=50)),
                ('category', models.CharField(choices=[('book', 'Book'), ('kit', 'Kit'), ('accessory', 'Accessory')], max_length=100)),
                ('sub_category', models.CharField(choices=[('textbook', 'TextBook'), ('workbook', 'WorkBook'), ('notebook', 'NoteBook'), ('languagebook', 'LanguageBook'), ('dibbook', 'DIBBook'), ('dibbook', 'DIBBook')], max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('product_description', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('pcs', 'Piece'), ('kg', 'Kilograms'), ('ltr', 'Liters'), ('box', 'Box'), ('pack', 'Pack')], max_length=20)),
                ('volume', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
