# Generated by Django 5.2 on 2025-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalproduct',
            name='sub_category',
            field=models.CharField(choices=[('textbook', 'TextBook'), ('workbook', 'WorkBook'), ('notebook', 'NoteBook'), ('languagebook', 'LanguageBook'), ('dibbook', 'DIBBook')], max_length=100),
        ),
    ]
