# Generated by Django 5.2 on 2025-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_educationalproduct_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalproduct',
            name='segment',
            field=models.CharField(choices=[('ois', 'OIS'), ('b2b', 'B2B'), ('ocse', 'OCSE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='sub_category',
            field=models.CharField(choices=[('textbook', 'TextBook'), ('workbook', 'WorkBook'), ('notebook', 'NoteBook'), ('languagebook', 'LanguageBook'), ('dibbook', 'DIBBook'), ('studentplanner', 'StudentPlanner'), ('crayons', 'Crayons')], max_length=100),
        ),
    ]
